@startuml
'https://plantuml.com/sequence-diagram
user -> système: selectionnerTexte
système -> système: detecterZoneSelect
système -> user: surlignageTexte
user -> système: ctrl+x
système -> système: copierDansPressePapier
système -> système: supprimerBuffer
système -> user: supprimerTexte

@enduml