@startuml
'https://plantuml.com/sequence-diagram
user -> système: placementCurseur
système -> user: placement
user -> système: clickCopyButton
système -> système: getCopyBuffer()
système -> user: Ajout dans zone de texte


@enduml