@startuml
'https://plantuml.com/sequence-diagram
user -> Editor: selectionnerTexte
Editor -> Editor: detecterZoneSelect
Editor -> user: surlignageTexte
user -> Editor: suppr
Editor -> Editor: supprimerBuffer
Editor -> user: supprimerTexte

@enduml