@startuml
'https://plantuml.com/sequence-diagram
user -> Editor: selectionnerTexte
user -> Editor: clickButton()
Editor -> Editor: detecterZoneSelect
Editor -> Editor: augmenteSelection
Editor -> user: surlignageTexte
@enduml