@startuml
'https://plantuml.com/sequence-diagram'
user -> Editeur: placementCurseur
Editeur -> user: AffichageCurseur
user -> Editeur: clickPasteButton
Editeur -> Editeur: CommandPaste.execute()
Editeur -> user: Ajout et remplacement dans zone de texte
@enduml