@startuml
'https://plantuml.com/sequence-diagram'
user -> Editor: placementCurseur
Editor -> user: AffichageCurseur
user -> Editor: clickPasteButton
Editor -> Editor: CommandPaste.execute()
Editor -> user: Ajout et remplacement dans zone de texte
@enduml