@startuml
'https://plantuml.com/sequence-diagram
user -> système: selectionnerTexte
système -> système: detecterZoneSelect
système -> user: surlignageTexte
user -> système: ClickCutButton
système -> système: CutCommand.execute()
système -> user: supprimerTexte
@enduml