@startuml
'https://plantuml.com/sequence-diagram
user -> Editor: selectionnerTexte
Editor -> Editor: detecterZoneSelect
Editor -> user: surlignageTexte
user -> Editor: ClickCutButton
Editor -> Editor: CutCommand.execute()
Editor -> user: supprimerTexte
@enduml