@startuml
'https://plantuml.com/sequence-diagram
user -> Editeur: selectionnerTexte
Editeur -> Editeur: detecterZoneSelect
Editeur -> user: surlignageTexte
user -> Editeur: ClickCutButton
Editeur -> Editeur: CutCommand.execute()
Editeur -> user: supprimerTexte
@enduml